name: Review Test

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Diff
        run: |
          git diff HEAD~1 HEAD
