name: Review Test

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check Git History
        run: |
          git log --oneline -n 5

      - name: Save Diff
        run: |
          {
            echo "DIFF<<EOF"
            git diff HEAD~1 HEAD
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Send Review Request
        run: |
          curl -X POST \
            "${{ secrets.REVIEW_API_URL }}" \
            -H "Content-Type: application/json" \
            --data "$DfIFF"